[project]
name = "chiaroscuro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorspacious>=1.1.2",
    "matplotlib>=3.10.8",
    "requests>=2.32.5",
]
